import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import { InventoryItem, ParsedPolicy } from '../types';

export const generateInventoryReport = (
    inventory: InventoryItem[], 
    policy: ParsedPolicy | undefined, 
    accountHolderName: string = 'Valued Policyholder'
) => {
    const doc = new jsPDF();
    const pageWidth = doc.internal.pageSize.width;

    // --- Header ---
    doc.setFontSize(22);
    doc.setTextColor(30, 41, 59); // Slate 800
    doc.text("VeritasVault", 14, 20);
    
    doc.setFontSize(14);
    doc.setTextColor(100, 116, 139); // Slate 500
    doc.text("Personal Property Inventory Report", 14, 28);

    doc.setFontSize(10);
    doc.text(`Generated on: ${new Date().toLocaleDateString()}`, 14, 35);
    doc.text(`Policyholder: ${accountHolderName}`, 14, 40);
    
    if (policy) {
        doc.text(`Policy Provider: ${policy.provider}`, pageWidth - 14, 35, { align: 'right' });
        doc.text(`Policy #: ${policy.policyNumber}`, pageWidth - 14, 40, { align: 'right' });
    }

    doc.setDrawColor(226, 232, 240); // Slate 200
    doc.line(14, 45, pageWidth - 14, 45);

    // --- Summary Statistics ---
    const totalItems = inventory.length;
    const totalValue = inventory.reduce((sum, item) => sum + item.originalCost, 0);
    const totalRCV = inventory.reduce((sum, item) => sum + (item.replacementCostValueRCV || item.originalCost), 0);

    doc.setFontSize(12);
    doc.setTextColor(30, 41, 59);
    doc.text("Summary", 14, 55);

    const summaryData = [
        ['Total Items', totalItems.toString()],
        ['Total Acquisition Cost', `$${totalValue.toLocaleString()}`],
        ['Total Replacement Value (RCV)', `$${totalRCV.toLocaleString()}`]
    ];

    autoTable(doc, {
        startY: 60,
        head: [['Metric', 'Value']],
        body: summaryData,
        theme: 'plain',
        styles: { fontSize: 10, cellPadding: 3 },
        headStyles: { fillColor: [241, 245, 249], textColor: [71, 85, 105], fontStyle: 'bold' },
        columnStyles: { 0: { fontStyle: 'bold', cellWidth: 80 } }
    });

    // --- Inventory Table ---
    doc.text("Detailed Inventory", 14, (doc as any).lastAutoTable.finalY + 15);

    const tableRows = inventory.map(item => [
        item.itemName,
        item.itemCategory,
        item.brand ? `${item.brand} ${item.model || ''}` : 'N/A',
        item.purchaseDate ? new Date(item.purchaseDate).toLocaleDateString() : 'Unknown',
        `$${item.originalCost.toLocaleString()}`,
        `$${(item.replacementCostValueRCV || item.originalCost).toLocaleString()}`
    ]);

    autoTable(doc, {
        startY: (doc as any).lastAutoTable.finalY + 20,
        head: [['Item Name', 'Category', 'Brand/Model', 'Purchase Date', 'Cost', 'RCV']],
        body: tableRows,
        theme: 'striped',
        styles: { fontSize: 9, cellPadding: 3 },
        headStyles: { fillColor: [79, 70, 229], textColor: 255, fontStyle: 'bold' }, // Indigo 600
        alternateRowStyles: { fillColor: [248, 250, 252] } // Slate 50
    });

    // --- Footer ---
    const pageCount = (doc as any).internal.getNumberOfPages();
    for (let i = 1; i <= pageCount; i++) {
        doc.setPage(i);
        doc.setFontSize(8);
        doc.setTextColor(148, 163, 184);
        doc.text(`Page ${i} of ${pageCount}`, pageWidth / 2, doc.internal.pageSize.height - 10, { align: 'center' });
        doc.text("Generated by VeritasVault", pageWidth - 14, doc.internal.pageSize.height - 10, { align: 'right' });
    }

    doc.save(`VeritasVault_Inventory_Report_${new Date().toISOString().split('T')[0]}.pdf`);
};
