import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import { InventoryItem, ParsedPolicy } from '../types';

export const generateInventoryReport = (
    inventory: InventoryItem[], 
    policy: ParsedPolicy | undefined, 
    accountHolderName: string = 'Valued Policyholder'
) => {
    const doc = new jsPDF();
    const pageWidth = doc.internal.pageSize.width;

    // --- Header ---
    doc.setFontSize(22);
    doc.setTextColor(30, 41, 59); // Slate 800
    doc.text("Assert", 14, 20);
    
    doc.setFontSize(14);
    doc.setTextColor(100, 116, 139); // Slate 500
    doc.text("Personal Property Inventory Report", 14, 28);

    doc.setFontSize(10);
    doc.text(`Generated on: ${new Date().toLocaleDateString()}`, 14, 35);
    doc.text(`Policyholder: ${accountHolderName}`, 14, 40);
    
    if (policy) {
        doc.text(`Policy Provider: ${policy.provider}`, pageWidth - 14, 35, { align: 'right' });
        doc.text(`Policy #: ${policy.policyNumber}`, pageWidth - 14, 40, { align: 'right' });
    }

    doc.setDrawColor(226, 232, 240); // Slate 200
    doc.line(14, 45, pageWidth - 14, 45);

    // --- Summary Statistics ---
    const totalItems = inventory.length;
    const totalValue = inventory.reduce((sum, item) => sum + item.originalCost, 0);
    const totalRCV = inventory.reduce((sum, item) => sum + (item.replacementCostValueRCV || item.originalCost), 0);

    doc.setFontSize(12);
    doc.setTextColor(30, 41, 59);
    doc.text("Summary", 14, 55);

    const summaryData = [
        ['Total Items', totalItems.toString()],
        ['Total Acquisition Cost', `$${totalValue.toLocaleString()}`],
        ['Total Replacement Value (RCV)', `$${totalRCV.toLocaleString()}`]
    ];

    autoTable(doc, {
        startY: 60,
        head: [['Metric', 'Value']],
        body: summaryData,
        theme: 'plain',
        styles: { fontSize: 10, cellPadding: 3 },
        headStyles: { fillColor: [241, 245, 249], textColor: [71, 85, 105], fontStyle: 'bold' },
        columnStyles: { 0: { fontStyle: 'bold', cellWidth: 80 } }
    });

    // --- Inventory Table ---
    doc.text("Schedule of Loss", 14, (doc as any).lastAutoTable.finalY + 15);

    const calculateAgeMonths = (dateStr: string | undefined) => {
        if (!dateStr) return 'N/A';
        const d = new Date(dateStr);
        if (isNaN(d.getTime())) return 'N/A';
        const now = new Date();
        const months = (now.getFullYear() - d.getFullYear()) * 12 + (now.getMonth() - d.getMonth());
        return Math.max(0, months).toString() + ' mo';
    };

    const tableRows = inventory.map(item => [
        "1", // Quantity
        item.itemName,
        `${item.brand || ''} ${item.model || ''}`.trim() || 'Unspecified',
        item.serialNumber || 'N/A',
        calculateAgeMonths(item.purchaseDate),
        item.condition || 'Average',
        `$${item.originalCost.toLocaleString()}`,
        `$${(item.replacementCostValueRCV || item.originalCost).toLocaleString()}`
    ]);

    autoTable(doc, {
        startY: (doc as any).lastAutoTable.finalY + 20,
        head: [['Qty', 'Description', 'Brand/Model', 'Serial #', 'Age', 'Condition', 'Cost', 'Unit RCV']],
        body: tableRows,
        theme: 'striped',
        styles: { fontSize: 8, cellPadding: 3 },
        headStyles: { fillColor: [51, 65, 85], textColor: 255, fontStyle: 'bold' }, // Slate 700 for professional look
        alternateRowStyles: { fillColor: [248, 250, 252] }, // Slate 50
        columnStyles: {
            0: { cellWidth: 10 },
            4: { cellWidth: 15 },
            5: { cellWidth: 18 },
            6: { cellWidth: 18, halign: 'right' },
            7: { cellWidth: 18, halign: 'right' }
        }
    });

    // --- Footer ---
    const pageCount = (doc as any).internal.getNumberOfPages();
    for (let i = 1; i <= pageCount; i++) {
        doc.setPage(i);
        doc.setFontSize(8);
        doc.setTextColor(148, 163, 184);
        doc.text(`Page ${i} of ${pageCount}`, pageWidth / 2, doc.internal.pageSize.height - 10, { align: 'center' });
        doc.text("Generated by Assert", pageWidth - 14, doc.internal.pageSize.height - 10, { align: 'right' });
    }

    doc.save(`Assert_Inventory_Report_${new Date().toISOString().split('T')[0]}.pdf`);
};
